version: "3.7"

services:
  idp:
    image: idp
    container_name: idp
    build:
      context: ./idp
      args:
        - JETTY_KEYSTORE_PASSWORD=storepwd
        - IDP_INSTALL_DSTDIR=/opt
        - IDP_INSTALL_SCOPE=example.org
        - IDP_INSTALL_HOST_NAME=idp.example.org
        - IDP_INSTALL_SEALER_PASSWORD=password
        - IDP_INSTALL_KEYSTORE_PASSWORD=password
        - IDP_INSTALL_ENTITY_ID=https://idp.example.org/idp/shibboleth
    restart: always
    tty: true
    volumes:
      - ./volumes/idp/conf:/opt/shibboleth-idp/conf
    ports:
      - 8080:8080 
  ldap:
    image: ldap
    container_name: ldap
    build:
      context: ./ldap
    ports:
      - 389:389
    environment:
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "password"
  sp:
    image: sp
    container_name: sp
    build:
      context: ./sp
    ports:
      - 10443:10443

